INSERT INTO products(name, price) VALUES ('Tablet', 500.87);
INSERT INTO products(name, price) VALUES ('Notebook', 5875.87);
INSERT INTO products(name, price) VALUES ('Caneta BIC Preta', 3.78);
INSERT INTO products(name, price) VALUES ('Caneta BIC Verde', 3.78);
INSERT INTO products(name, price) VALUES ('Caneta BIC Vermelha', 3.78);
INSERT INTO products(name, price) VALUES ('Caneta BIC Azul', 3.78);
INSERT INTO products(name, price) VALUES ('Caneta BIC Pink', 3.78);
INSERT INTO products(name, price) VALUES ('Caneta BIC Lilas', 3.78);
INSERT INTO products(name, price) VALUES ('Caneta BIC Laranja', 3.78);
INSERT INTO products(name, price) VALUES ('Samsung A20', 1485.87);
INSERT INTO products(name, price) VALUES ('Xiaomi MI 11', 5875.87);
INSERT INTO products(name, price) VALUES ('Monitor 23.5	', 1587.87);
INSERT INTO products(name, price) VALUES ('Gabinete Redragon', 456.43);
INSERT INTO products(name, price) VALUES ('SSD Kingston 240GB', 280.87);
INSERT INTO products(name, price) VALUES ('Macbook Pro', 15875.87);
INSERT INTO products(name, price) VALUES ('Tinta de cabelo', 5.87);
INSERT INTO products(name, price) VALUES ('Teste', 5.87);
INSERT INTO products(name, price) VALUES ('Cadeira Gamer', 587.87);
INSERT INTO products(name, price) VALUES ('Teste', 5.87);
INSERT INTO products(name, price) VALUES ('Mesa de escritório', 275.87);
INSERT INTO products(name, price) VALUES ('Teste', 5.87);
INSERT INTO products(name, price) VALUES ('Mouse Gamer Redragon', 120.45);
INSERT INTO products(name, price) VALUES ('Camiseta Preta', 25.57);
INSERT INTO products(name, price) VALUES ('Calça Jeans', 85.97);
INSERT INTO products(name, price) VALUES ('Cooler para processador', 240.87);
